version: '3'
services:
  aeon-wallet:
    build:
      context: .
      args:
        - GIT_TAG=v0.9.14.0
        - GIT_REPO=https://github.com/aeonix/aeon.git
        - WALLET_BIN=simplewallet
        - WALLET_DAEMON_BIN=aeond
    container_name: aeon-wallet
    environment:
        - WALLET_NAME=pool.bin
        - WALLET_PASSWORD=""
        - WALLET_PORT=11188
        - WALLETD_PORT=11181
    volumes:
      - wallet-data-aeon:/wallet
   
volumes:
  wallet-data-aeon: 

networks:
  default:
    external:
      name: "crypto-pool-net"
