version: '3'
services:
  haproxy:
    build: .
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
      - "3333:3333"
      - "3334:3334"
      - "3335:3335"
      - "8117:8117"
      - "8119:8119"
      - "9999:9999"
    volumes:
      - haproxy-data:/etc/letsencrypt
    env_file: /$PWD/../crypto-pool-env
    environment:
      - HAPROXY_STATS_PASSWORD=readme
      - HAPROXY_STATS_PORT=9999
      - AEON_WEB_DOMAIN=aeon.magiclobster.de
      - MONERO_WEB_DOMAIN=monero.magiclobster.de
      - MINER_PORT_LOW=3333
      - MINER_PORT_MED=3334
      - MINER_PORT_HIG=3335
      - POOL_API_PORT=8117
      - POOL_API_PORT_SSL=8119

volumes:
  haproxy-data:

networks:
  default:
    external:
      name: "crypto-pool-net"
